root = "."
tmp_dir = "tmp"
[build]
cmd = "go build -o tmp/main ./cmd/app/main.go"
bin = "tmp/main"

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true